input-file: main.tex
output-file: document.docx

filters:
    - latex2docx/filter.py
    - pandoc-crossref
    - citeproc
metadata:
    autoEqnLabels: true
    nameInLink: true

reference-doc: latex2docx/reference.docx

csl: latex2docx/physical-review-letters.csl
bibliography: references.bib

